### ISSUE TITLE
Gyro library X and Y values are between -90 and 90

### ISSUE THREAD

**Issue by EliKrumholz** [Makeblock-official/Makeblock-Libraries#11]
Is there a reason why gyro.getAngleX() and gyro.getAngleY() return values between -90 and 90 while gyro.getAngleZ() returns values between -180 and 180? Why not return values between -180 and 180 for all angles?

**Comment by YanMinge** [comment]
thanks for your comments. I will update next version.

**Comment by clplaneguy** [comment]
I have found the example programs for the gyro module and the wall avoider.  I have enhanced both for my use.  Then I combined the two use the gyro in the wall avoider.  The example programs work exactly as expected.  But on the combination program, the gyro.getAngleZ() value is never accurate.  The gyro can not keep up if other things are happining.  

And you could return all angles between 0 and 360.

/**
 *
 *
 * @file    Ivany10.ino
 * @author  MAM
 * @version V1.0.0
 * @date    11/2/2016
 * @brief   Description: This program started with the original code for the Mbot.
 *
 * Function List:
 * 1. void MeGyro::begin(void)
 * 2. void MeGyro::update(void)
 * 3. double MeGyro::angleX(void)
 * 4. double MeGyro::angleY(void)
 * 5. double MeGyro::angleZ(void)
 *
 * \par History:
 * <pre>
 * <Author>     <Time>        <Version>      <Descr>
 * Mark Yan     2015/09/09    1.0.0          rebuild the old lib "Wall Avoider.ino"
 * MAM          10/24/2016    1.0.0          Convert to MegaPi   "Wall Avoider.ino"
 * MAM          10/25/2016    1.0.1          Increase avoidance distance
 * MAM          10/26/2016    1.0.0          File name Ivany
 * MAM          10/27/2016    1.0.0          Rename Ivany2.ino  5:01PM Remane Ivany4.ino Use Boolean switch and counter.  5:33PM Works great.  Move on to version 5 with more code. Include gyro.
 * MAM          10/27/2016    1.0.0          Saved as Ivany5.ino
 * MAM          10/31/2016    1.0.0          Saved as Ivany8.ino
 * MAM          11/1/2016     1.0.0          Printed 6 point in Notepad.  Try 4 point.  Typed in hard copy corrections.  Has been tweeked.  Works great.  Left ONLY.  Saved as Ivany9.ino
 * MAM          11/2/2016     1.0.0          Add code for 'Too close too wall, back up'.  Saved as Ivany10.ino  Now does left and right.
 * </pre>
 *
 */

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

#include <MeMegaPi.h>

MeUltrasonicSensor ultraSensor(PORT_7); /* Ultrasonic module can ONLY be connected to port 3, 4, 6, 7, 8 of base shield. */
MeGyro gyro;
//Encoder Motor
MeEncoderOnBoard Encoder_1(SLOT1);
MeEncoderOnBoard Encoder_2(SLOT2);


float Value;
/* boolean Right;
/*
 *MeEncoderOnBoard Encoder_3(SLOT3);
 *MeEncoderOnBoard Encoder_4(SLOT4);
*/

void isr_process_encoder1(void)                        //
{ //
  if (digitalRead(Encoder_1.getPortB()) == 0)          //
  { //
    Encoder_1.pulsePosMinus();                         //
  }                                                    //
  else {                                               //
    Encoder_1.pulsePosPlus();                          //
  }                                                    //
}                                                      //


void isr_process_encoder2(void) {                      //
  if (digitalRead(Encoder_2.getPortB()) == 0)
  { //
    Encoder_2.pulsePosMinus();                         //
  }                                                    //
  else {  //
    Encoder_2.pulsePosPlus();                          //
  }                                                    //
}                                                      //


/*                                                     //
void isr_process_encoder3(void)
{                       //
      if(digitalRead(Encoder_3.getPortB()) == 0){      //
            Encoder_3.pulsePosMinus();}                //
      else{
            Encoder_3.pulsePosPlus();}}                //

void isr_process_encoder4(void)                        //
{                                                      //
      if(digitalRead(Encoder_4.getPortB()) == 0){      //
            Encoder_4.pulsePosMinus();}                //
      else{                                            //
            Encoder_4.pulsePosPlus();}}                //
*/                                                     //
//
//
void move(double distance, int direction, int speed)                             //
//
{ //
  int leftSpeed  = 0;                                                            //
  int rightSpeed = 0;                                                            //
  Serial.print (" Distance is eactly ");                                                   //
  Serial.print (distance);                                                       //
  if (direction == 1)                                                            //
    //
  { //
    Serial.println  ("    'Move' Forward");                                             //
    leftSpeed = -speed;                                      /* 1 Forward  */    //
    rightSpeed = speed;                                                          //
  }                                                                              //
  //
  else if (direction == 2)                                                       //
    //
  {
    Serial.println    ("    'Move' Backward         ");       /* 2 Backward */         //
    leftSpeed = speed;                                                           //
    rightSpeed = -speed;                                                         //
  }                                                                              //
  //
  else if (direction == 3)                                                       //
    //
  {
    Serial.println  ("    'Move' Left");     /* 3 Left     */   //                      //
    leftSpeed = speed;                                                           //
    rightSpeed = speed;                                                          //
  }                                                                              //
  //
  else if (direction == 4)                                                       //
    //
  {  //
    Serial.println  ("    'Move' Right");        /* 4 Right    */                       //
    leftSpeed = -speed;                                                          //
    rightSpeed = -speed;                                                         //
  }                                                                              //
  //
  Encoder_1.setTarPWM(rightSpeed);
  Encoder_2.setTarPWM(leftSpeed);
}


void moveDegrees(int direction, long degrees, int speed_temp) {
  speed_temp = abs(speed_temp);
  if (direction == 1) {                                              /* 1 Forward */
    Encoder_1.move(degrees, (float)speed_temp);
    Encoder_2.move(-degrees, (float)speed_temp);
  }
  else if (direction == 2) {                                         /* 2 Backward */
    Encoder_1.move(-degrees, (float)speed_temp);
    Encoder_2.move(degrees, (float)speed_temp);
  }
  else if (direction == 3) {                                         /* 3 Left */
    Encoder_1.move(degrees, (float)speed_temp);
    Encoder_2.move(degrees, (float)speed_temp);
  }
  else if (direction == 4) {                                         /* 4 Right */
    Encoder_1.move(-degrees, (float)speed_temp);
    Encoder_2.move(-degrees, (float)speed_temp);
  }
}


double angle_rad = PI / 180.0;
double angle_deg = 180.0 / PI;
double speed;
double distance;
int x, count;
boolean Left = 1;

void setup() {
  //Set Pwm 8KHz
  TCCR1A = _BV(WGM10);
  TCCR1B = _BV(CS11) | _BV(WGM12);
  TCCR2A = _BV(WGM21) | _BV(WGM20);
  TCCR2B = _BV(CS21);
  Serial.begin(9600);
  Serial.println(" ");
  Serial.println("Start Setup");
  gyro.begin();
  int LeftCount = 0;
  attachInterrupt(Encoder_1.getIntNum(), isr_process_encoder1, RISING);
  attachInterrupt(Encoder_2.getIntNum(), isr_process_encoder2, RISING);
  //  speed = 100;
  speed = 100;  //  Minimum
  gyro.update();
  delay(100); /* the minimal measure interval is 100 milliseconds */
  Serial.println("End Setup");
}

void loop()

{
  int LeftCount;
  double Turn = 123, Heading = 456, temp = 789;
  int Mindis;

  Serial.println("Start loop ");
  distance = ultraSensor.distanceCm();
  delay(100); // The minimum delay interval for the ultrasonic sensor module is 100 milliseconds

  gyro.update();
  Serial.print("                         Distance is ");
  Serial.print(ultraSensor.distanceCm() );
  Serial.print(" cm      ");
  Serial.print("   X:");
  Serial.print(gyro.getAngleX() );
  Serial.print(" degres   Y:");
  Serial.print(gyro.getAngleY() );
  Serial.print(" degres   Z:(raw)");
  Serial.print(gyro.getAngleZ() );
  Serial.print(" degres  Heading is ");
  Heading = gyro.getAngleZ() + 360;
  if (Heading > 360) Heading = Heading - 360;
  Serial.print(Heading);
  Serial.println(" degres.   End of intro");


  if (gyro.getAngleY() <= -45)

  { //  Begin ' if (gyro.getAngleY() <= -45)'
    move(distance, 20, speed);                        /* 2 Backward */
    _delay(1);
  }    //  End 'if (gyro.getAngleY() <= -45)'

  //          distance = GoodDistance();

  //  distance = 100;  //  Debug statment
  Mindis = 40;
  if (distance < Mindis) 
  
  {  //  Begin if close to wall turn

    Serial.println("Close to wall");
    if (distance<25)

    {  //  Begin if too close to wall backup
      move(distance,2,speed);  //  Backward
      _delay(0.5);
      Serial.println("Too close to wall.  Backing up");
     
    }  //  End if too close to wall

    while (distance <= Mindis)

    { //  Begin while close to wall  --  Turn
      Serial.println("While close to wall  --  Turn");
      //      Left = 1;  //  Debug statment
//      Left = 0;  //  Debug statment
      if (Left)

      { // Begin left turn                                                        Left

        gyro.begin();
        Serial.print("If (Left) exicute this code.");
        move(distance, 3, speed);               /* 3 Direction is left */
        _delay(1);
        LeftCount = LeftCount + 1;
        Turn = 1;                                                               //  Left turn loop starts with Turn at 1 dergee
        //                     Turn = 100;  //  Debug statement

        while (Turn < 1)

        { //  Begin  --  while turn is less than five degres            
          Serial.print("While turn is less than 5 degres loop.                Left turn is less than 90 degres.  Heading2 is ");
          Serial.print(Heading);
          Serial.print(" degres");
          Serial.print("  Turn is only ");
          Serial.print(Turn);
          Serial.println(" degres.");
          gyro.update();
          Turn = 2;                                                          //  Turn in while loop is 2    
          move(distance, 3, speed);              /* 3 Left */
          _delay(1);
          delay(10);
          distance = GoodDistance();
          Heading = gyro.getAngleZ() + 360;
          delay(2000);  //  The minimum delay interval for the gyroscope module is 10 ms.
          _delay(1);
          if (Heading > 360) Heading = Heading - 360;
          //                        delay(100);

          Turn = Heading;
          if (Heading > 180)

          { //  Begin 'if (Heading > 180)'
            Turn = 3;                                                   //  In tight loop Turn is 3
            Serial.print("                                                                                          In tight loop, Heading1 is ");
            Serial.print(Heading);
            Serial.print(" degres.  Turn is ");
            Serial.println(Turn);
          }  //   End 'if(Heading > 180)'

     
          delay(10);
          move(distance,1,0);
          move(distance,2,0);
          move(distance,3,0);
          move(distance,4,0);
          delay(100);
          distance = GoodDistance();
          delay(100);
          
        }     //  End  --  while turn is less than five degres   

        //                   Serial.print("                                   Turn is MORE THAN 90 degres");
      }  //  End 'if (Left)'      // Turn left        if turning left

      else

      { // Begin Right turn                                                         Right
        
        Serial.print("If (Right) exicute this code.");
        gyro.begin();
        move(distance, 4, speed);               /* 4   --  Right   */
        _delay(1);
        Turn = 1;                                                               //  1  If Right
        //                     Turn = 100;  //  Debug statement

        while (Turn < 1)

        { //  Begin  (while turn is too small)
          Serial.print("While turn is less than 5 degres loop.                Right turn is less than 5 degres.  Heading2 is ");
          Serial.print(Heading);
          Serial.print(" degres");
          Serial.print("  Turn is only ");
          Serial.print(Turn);
          Serial.println(" degres.");
          Turn = 2;                                                          //  2  Turn < 90
          move(distance, 4, speed);              /* 4 Right */
          _delay(0.5);
          move(distance,4, 0);
          delay(1);
          gyro.update();
          delay(10);  //  The minimum delay interval for the gyroscope module is 10 ms.
          delay(10);
          distance = GoodDistance();
          Heading = gyro.getAngleZ() + 360;
          delay(200);  //  The minimum delay interval for the gyroscope module is 10 ms.
          if (Heading>360) Heading = Heading - 360;
          //                        delay(100);

          Turn = 360 - Heading;
          if (Heading < 180)

          { //  Begin 'if (Heading < 180)'
            Turn = 3;                                                   //  3 Heading > 180
            Serial.print("                                                                                          In tight loop, Heading1 is ");
            Serial.print(Heading);
            Serial.print(" degres.  Turn is ");
            Serial.println(Turn);
          }  //   End 'if(Heading < 180)'

          delay(10);
          move(distance,1,0);
          move(distance,2,0);
          move(distance,3,0);
          move(distance,4,0);
          delay(100);
          distance = GoodDistance();
          delay(100);

        }     //  End (while turn is too small)


        //                   Serial.print("                                   Turn is MORE THAN 90 degres");
      }  //  End Right turn
      
      distance = GoodDistance();
    }  //  End while too close to wall

    Left = !Left;

  }    //  End if close to wall


  else

  { //  Else move forward
    move(distance, 1, speed); /* 1 Forward */
    _delay(1);
    Serial.println("Forward");
  }   //  End esle move forward

  _loop();

}  //  End 'void loop()'


void _delay(float seconds) 

{
  long endTime = millis() + seconds * 1000;
  while (millis() < endTime)_loop();
}



void _loop() 

{
  Encoder_1.loop();
  Encoder_2.loop();
}


float GoodDistance() 

{
  distance  = 0;
  for (x = 1; x <= 5; x++) {

    distance = distance + ultraSensor.distanceCm();
    delay(100);
    //           Serial.print(x);
  }  //   for (x = 1; x <= 5; x++){

  distance = distance / 5;
  return distance;
}  //   float GoodDistance(){
