### ISSUE TITLE
mBot mCore card support

### ISSUE THREAD

**Issue by benoit-pereira-da-silva** [Makeblock-official/Makeblock-Libraries#15]
Arduino - 1.6.8
OSX - 10.11.6 (15G31)
mBot - Blue (Bluetooth Version) with a mCore card.

1. I ve copied the files from the makeBlock Library into the app content package. (note that there is a typo error in your read me /java/ not /jave/ ) 
2. I ve restarted the Arduino app
3. The samples are available but not the card.
4. I ve have imported : #include "MeMCore.h"
4. And tryed to compile some samples  (screen shot attached) 

<img width="1680" alt="error" src="https://cloud.githubusercontent.com/assets/963307/17974771/ab772ea6-6ae7-11e6-80c6-bfaadc29e29c.png">

<img width="1680" alt="1" src="https://cloud.githubusercontent.com/assets/963307/17974274/bdca2aba-6ae5-11e6-92c1-9e5d00093145.png">
<img width="1680" alt="2" src="https://cloud.githubusercontent.com/assets/963307/17974276/be0ddb8e-6ae5-11e6-8624-2ad85d1b1eb7.png">
<img width="1680" alt="3" src="https://cloud.githubusercontent.com/assets/963307/17974275/be06e69e-6ae5-11e6-95be-47e06e9a0bd2.png">

**Comment by YanMinge** [comment]
Hi, seems it is not a compile error. if you use OSX, why you have COM1? it only will found on windows.

**Comment by YanMinge** [comment]
you should select the correct port and board on tools

**Comment by benoit-pereira-da-silva** [comment]
Thanks @YanMinge i have been able to fix the communication issue.
