### ISSUE TITLE
Ultrasonic module incompatable with gyro module

### ISSUE THREAD

**Issue by clplaneguy** [Makeblock-official/Makeblock-Libraries#19]
I have found the example programs for the gyro module and the wall avoider. I have enhanced both for my use. Then I combined the two to use the gyro in the wall avoider. The enhanced example programs work exactly as expected. But on the combination program, the gyro.getAngleZ() value is never accurate. Upon movement(left right) he gyro drifts to very unexcepable levels.  The avoider code includes lots of other routines.  The imported motor routines seem to block the ultrasonic module.  Following is the shortist program I can write that includes code for both.  The values for gyro.getAngleZ() are incorrect!

/**
 *
 *
 * @file    Ivany10.ino
 * @author  MAM
 * @version V1.0.0
 * @date    11/2/2016
 * @brief   Description: This program started with the original code for the Mbot.
 *
 * Function List:
 * 1. void MeGyro::begin(void)
 * 2. void MeGyro::update(void)
 * 3. double MeGyro::angleX(void)
 * 4. double MeGyro::angleY(void)
 * 5. double MeGyro::angleZ(void)
 *
 * \par History:
 * <pre>
 * <Author>     <Time>        <Version>      <Descr>
 * Mark Yan     2015/09/09    1.0.0          rebuild the old lib "Wall Avoider.ino"
 * MAM          10/24/2016    1.0.0          Convert to MegaPi   "Wall Avoider.ino"
 * MAM          10/25/2016    1.0.1          Increase avoidance distance
 * MAM          10/26/2016    1.0.0          File name Ivany
 * MAM          10/27/2016    1.0.0          Rename Ivany2.ino  5:01PM Remane Ivany4.ino Use Boolean switch and counter.  5:33PM Works great.  Move on to version 5 with more code. Include gyro.
 * MAM          10/27/2016    1.0.0          Saved as Ivany5.ino
 * MAM          10/31/2016    1.0.0          Saved as Ivany8.ino
 * MAM          11/1/2016     1.0.0          Printed 6 point in Notepad.  Try 4 point.  Typed in hard copy corrections.  Has been tweeked.  Works great.  Left ONLY.  Saved as Ivany9.ino
 * MAM          11/2/2016     1.0.0          Add code for 'Too close too wall, back up'.  Saved as Ivany10.ino  Now does left and right.
 * </pre>
 *
 */

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

#include <MeMegaPi.h>

MeUltrasonicSensor ultraSensor(PORT_7); /* Ultrasonic module can ONLY be connected to port 3, 4, 6, 7, 8 of base shield. */
MeGyro gyro;
//Encoder Motor
MeEncoderOnBoard Encoder_1(SLOT1);
MeEncoderOnBoard Encoder_2(SLOT2);

float Value;
/* boolean Right;
/*
 *MeEncoderOnBoard Encoder_3(SLOT3);
 *MeEncoderOnBoard Encoder_4(SLOT4);
*/

void isr_process_encoder1(void)                        //
{ //
  if (digitalRead(Encoder_1.getPortB()) == 0)          //
  { //
    Encoder_1.pulsePosMinus();                         //
  }                                                    //
  else {                                               //
    Encoder_1.pulsePosPlus();                          //
  }                                                    //
}                                                      //

void isr_process_encoder2(void) {                      //
  if (digitalRead(Encoder_2.getPortB()) == 0)
  { //
    Encoder_2.pulsePosMinus();                         //
  }                                                    //
  else {  //
    Encoder_2.pulsePosPlus();                          //
  }                                                    //
}                                                      //

/*                                                     //
void isr_process_encoder3(void)
{                       //
      if(digitalRead(Encoder_3.getPortB()) == 0){      //
            Encoder_3.pulsePosMinus();}                //
      else{
            Encoder_3.pulsePosPlus();}}                //

void isr_process_encoder4(void)                        //
{                                                      //
      if(digitalRead(Encoder_4.getPortB()) == 0){      //
            Encoder_4.pulsePosMinus();}                //
      else{                                            //
            Encoder_4.pulsePosPlus();}}                //
*/                                                     //
//
//
void move(double distance, int direction, int speed)                             //
//
{ //
  int leftSpeed  = 0;                                                            //
  int rightSpeed = 0;                                                            //
  Serial.print (" Distance is eactly ");                                                   //
  Serial.print (distance);                                                       //
  if (direction == 1)                                                            //
    //
  { //
    Serial.println  ("    'Move' Forward");                                             //
    leftSpeed = -speed;                                      /* 1 Forward  */    //
    rightSpeed = speed;                                                          //
  }                                                                              //
  //
  else if (direction == 2)                                                       //
    //
  {
    Serial.println    ("    'Move' Backward         ");       /* 2 Backward */         //
    leftSpeed = speed;                                                           //
    rightSpeed = -speed;                                                         //
  }                                                                              //
  //
  else if (direction == 3)                                                       //
    //
  {
    Serial.println  ("    'Move' Left");     /* 3 Left     */   //                      //
    leftSpeed = speed;                                                           //
    rightSpeed = speed;                                                          //
  }                                                                              //
  //
  else if (direction == 4)                                                       //
    //
  {  //
    Serial.println  ("    'Move' Right");        /* 4 Right    */                       //
    leftSpeed = -speed;                                                          //
    rightSpeed = -speed;                                                         //
  }                                                                              //
  //
  Encoder_1.setTarPWM(rightSpeed);
  Encoder_2.setTarPWM(leftSpeed);
}

void moveDegrees(int direction, long degrees, int speed_temp) {
  speed_temp = abs(speed_temp);
  if (direction == 1) {                                              /* 1 Forward */
    Encoder_1.move(degrees, (float)speed_temp);
    Encoder_2.move(-degrees, (float)speed_temp);
  }
  else if (direction == 2) {                                         /* 2 Backward */
    Encoder_1.move(-degrees, (float)speed_temp);
    Encoder_2.move(degrees, (float)speed_temp);
  }
  else if (direction == 3) {                                         /* 3 Left */
    Encoder_1.move(degrees, (float)speed_temp);
    Encoder_2.move(degrees, (float)speed_temp);
  }
  else if (direction == 4) {                                         /* 4 Right */
    Encoder_1.move(-degrees, (float)speed_temp);
    Encoder_2.move(-degrees, (float)speed_temp);
  }
}

double angle_rad = PI / 180.0;
double angle_deg = 180.0 / PI;
double speed;
double distance;
int x, count;
boolean Left = 1;

void setup() {
  //Set Pwm 8KHz
  TCCR1A = _BV(WGM10);
  TCCR1B = _BV(CS11) | _BV(WGM12);
  TCCR2A = _BV(WGM21) | _BV(WGM20);
  TCCR2B = _BV(CS21);
  Serial.begin(9600);
  Serial.println(" ");
  Serial.println("Start Setup");
  gyro.begin();
  int LeftCount = 0;
  attachInterrupt(Encoder_1.getIntNum(), isr_process_encoder1, RISING);
  attachInterrupt(Encoder_2.getIntNum(), isr_process_encoder2, RISING);
  //  speed = 100;
  speed =300;  //  Minimum
  gyro.update();
  delay(100); /* the minimal measure interval is 100 milliseconds */
  Serial.println("End Setup\nBegin loop");
}

void loop()

{
  double  Heading = 456;
 
  distance = ultraSensor.distanceCm();
  delay(100); // The minimum delay interval for the ultrasonic sensor module is 100 milliseconds
  gyro.update();
  Serial.print("Distance is ");
  Serial.print(ultraSensor.distanceCm() );
  Serial.print(" cm      ");
  Serial.print("        X:");
  Serial.print(gyro.getAngleX() );
  Serial.print(" degrees        Y:");
  Serial.print(gyro.getAngleY() );
  Serial.print(" degrees        Z:(raw)");
  Serial.print(gyro.getAngleZ() );
  Serial.print(" degrees                 Heading is ");
  Heading = gyro.getAngleZ() + 360;
  if (Heading > 360) Heading = Heading - 360;
  Serial.print(Heading);
  Serial.println(" degrees.                                    End of print");
  delay(100);

}  //  End 'void loop()'

void _delay(float seconds) 

{
  long endTime = millis() + seconds * 1000;
  while (millis() < endTime)_loop();
}

void _loop() 

{
  Encoder_1.loop();
  Encoder_2.loop();
}

**Comment by YanMinge** [comment]
Yes, since we need support offline and online block programming, the code structure and algorithm are not perfect. if You have delay in loop, the gyroscope module can‘t be updated in time. And the Z axis don't have third-party observers, It is indeed drift.
