### ISSUE TITLE
MegaPi for balancing bot

### ISSUE THREAD

**Issue by rutadesai** [Makeblock-official/Makeblock-Libraries#22]
Hi there,

When I try to upload firmware_for_megapi onto my megapi controller, it gives errors (such as redefinition of Servo and other components etc). Any idea why?

Can you share the code for balancing bot with megapi? I want to customize it and its hard to do from within the phone app.

Thanks.

**Comment by dobbyzzipeng** [comment]
hi,show me the error messages with a picture please.
