### ISSUE TITLE
can't compile downloaded firmware

### ISSUE THREAD

**Issue by shupack** [Makeblock-official/Makeblock-Libraries#24]
I downloaded the most recent .zip, opened in arduino and attempted to compile, no modifications. Errors as follow:
`

C:\Users\DENNIS~1\AppData\Local\Temp\ccm9UQo8.ltrans0.ltrans.o: In function `runModule':

C:\Users\Dennis Altman\Documents\Arduino\starter_factory_firmware_modified/starter_factory_firmware_modified.ino:525: undefined reference to `Servo::attached()'

C:\Users\Dennis Altman\Documents\Arduino\starter_factory_firmware_modified/starter_factory_firmware_modified.ino:527: undefined reference to `Servo::attach(int)'

C:\Users\Dennis Altman\Documents\Arduino\starter_factory_firmware_modified/starter_factory_firmware_modified.ino:529: undefined reference to `Servo::write(int)'

C:\Users\DENNIS~1\AppData\Local\Temp\ccm9UQo8.ltrans2.ltrans.o: In function `__static_initialization_and_destruction_0':

C:\Users\Dennis Altman\Documents\Arduino\starter_factory_firmware_modified/starter_factory_firmware_modified.ino:17: undefined reference to `Servo::Servo()'

collect2.exe: error: ld returned 1 exit status

Multiple libraries were found for "MeOrion.h"
 Used: C:\Program Files (x86)\Arduino\libraries\src
 Not used: C:\Program Files (x86)\Arduino\libraries\makeblock
 Not used: C:\Program Files (x86)\Arduino\libraries\makeblock
 Not used: C:\Program Files (x86)\Arduino\libraries\makeblock
 Not used: C:\Program Files (x86)\Arduino\libraries\makeblock
exit status 1
Error compiling for board Arduino/Genuino Uno.
`

**Comment by Makeblock-official** [comment]
You can refer to our firmware example -> starter_factory_firmware
if you want use servo, you need include <Wire.h>
