### ISSUE TITLE
Can't compile: 'class MeEncoderNew' has no member named 'GetCurrentSpeed'

### ISSUE THREAD

**Issue by Daemon2017** [Makeblock-official/Makeblock-Libraries#26]
Hello! 
Library installed as in manual, but the result is 'class MeEncoderNew' has no member named 'GetCurrentSpeed'.
![image](https://cloud.githubusercontent.com/assets/5642326/23042903/891b470e-f4ab-11e6-9771-8964de3efcfc.png)

**Comment by dobbyzzipeng** [comment]
hello,have you included the head code?like this:
![image](https://cloud.githubusercontent.com/assets/13638394/23049495/705daa30-f4f7-11e6-9813-d5c133c82173.png)

**Comment by Daemon2017** [comment]
Hello!

I've tried to change, but  it doesn't help:
![image](https://cloud.githubusercontent.com/assets/5642326/23055726/66b8967e-f4f8-11e6-9df4-92b583ae1c09.png)

What else could be wrong in my code?

**Comment by Daemon2017** [comment]
Hello! 

Here is a problem:
In documentation on maleblock's site: float currentSpeed = motor1.GetCurrentSpeed();
Working code: float currentSpeed = motor1.getCurrentSpeed();

So, now everything is great :)

**Comment by dobbyzzipeng** [comment]
hi,you are right.Open the MeEncoderNew.cpp code and make sure the method "GetCurrentSpeed" is in it.
like this:
![image](https://cloud.githubusercontent.com/assets/13638394/23055890/5342735a-f523-11e6-9392-a5592ef17925.png)

if not,you should update your libraries.

**Comment by Makeblock-official** [comment]
You should update your libraries.
