### ISSUE TITLE
ledmatrix, show face x,y, characters function cannot use a String variable inside a data block

### ISSUE THREAD

**Issue by edwardotis** [Makeblock-official/Makeblock-Libraries#28]
http://forum.makeblock.com/t/the-latest-version-mblock-2-2-0-has-released-on-mblock-cc/1548/5?u=edwardotis

ledmatrix, show face x,y, characters function cannot use a String variable inside a data block. 
The code that compiles from Scratch to Arduino C code is broken.

Current broken implementation:
 It uses the quoted variable **name** instead of using the **value** of the String variable. 

Corrected implementation:
Convert the String variable into a char array using String::c_str()

Affected Versions:
This has been broken since 2.2.0 according to the forum post.
Still broken today in v3.4.6

**Comment by MrHezhisheng** [comment]
About this issue ,I've already spoken to the makeblock project team.but they replied that this feature was not supported now!
