### ISSUE TITLE
ColorSensor.h

### ISSUE THREAD

**Issue by Robotonics** [Makeblock-official/Makeblock-Libraries#29]
file ColorSensor.h is mispelled as Colorsensor.h in MeOrion.h

**Comment by dobbyzzipeng** [comment]
ok,i will change it tomorrow~thanks

**Comment by jhagberg** [comment]
I guess it is the same in MeMcore.h
fatal error: MeColorsensor.h: No such file or directory
 #include "MeColorsensor.h"

**Comment by jipp** [comment]
Hi

yes, its the same in MeMCore.h.

this is as well causing problem during compile time

cheers

**Comment by jhagberg** [comment]
Yes I have made a PullReq #30 fixing this
