### ISSUE TITLE
problem with block [set encoder motor on board ... rotate ... degrees at speed ... rpm]

### ISSUE THREAD

**Issue by tschmit** [Makeblock-official/Makeblock-Libraries#35]
using: 
* MeAuriga
* mBlock 3.4.5
* windows 10 (app installed from windows store)

![image](https://cloud.githubusercontent.com/assets/3993568/26395006/14aad938-406f-11e7-8a61-d81c8fd66b9f.png)

It seems that the parameter `degrees` is ignored. The motor starts rotating and never stops.

**Comment by YanMinge** [comment]
It seems that the feedback of the motor should not be normal. You can try to read the motor speed, if the motor speed is not properly updated, the motor connection may be faulty.

And our latest version of the mblock is 3.4.8, you can look at the update record, whether there are related defects

**Comment by tschmit** [comment]
I just updated to 3.4.8 and still have the problem.
Under Linux with version 4 the bloc does not exists ? Does that mean that it will be discarded ?

**Comment by tschmit** [comment]
I write the following program, and the leds stays red :(

![image](https://cloud.githubusercontent.com/assets/3993568/26398956/7ccc7dc6-407b-11e7-9d8d-fe62e8725ef2.png)

The problems seems to be the one you point... what can I do ?

**Comment by tschmit** [comment]
I finally make tests:
- with another auriga, I have the same behavior: my motor never stops
- with another motor: the another motor starts then stops after completing the required degrees.

My motors are (both !!!) defective!

**Comment by YanMinge** [comment]
May be just the cable is broken.

**Comment by tschmit** [comment]
unfortunately not. I use my cable with the other motor. And all run well.

**Comment by YanMinge** [comment]
You can go our after-sales process, and I will close this issue.
