### ISSUE TITLE
Wrong example for Me_Megapi_encoder_direct

### ISSUE THREAD

**Issue by matteosuppo** [Makeblock-official/Makeblock-Libraries#37]
@https://github.com/Makeblock-official/Makeblock-Libraries/tree/master/makeblock/examples/Me_On_Board_encoder/Me_Megapi_encoder_direct

It contains `Me_Auriga_encoder_direct.ino`

**Comment by 00alis** [comment]
Any update on this? It still fails when trying to import on https://create.arduino.cc/editor
thanks!

**Comment by LanWting** [comment]
@matteosuppo
Thank you for finding a bug, according to the path has been modified, please update the latest document.
