### ISSUE TITLE
RGB Line follower example using arduino

### ISSUE THREAD

**Issue by nikhilabhi** [Makeblock-official/Makeblock-Libraries#63]
Can you please give us RGB LIne follower using code to do with arduino? I tried doing it with line follower example code but i were getting false reading because rgb line follower is having four different ir sensors while line follower is having two IR sensors.

**Comment by nikhilabhi** [comment]
I have written my own code to arduino and now it is working fine.

**Comment by halilpolathalil** [comment]
Hi, Could you share example code please? I am developing line follower robot with this sensor and arduino.  I want to use mblock. If you sahre, I want to use for Mblock. Thank you
