### ISSUE TITLE
what's the purpose of these codes?

### ISSUE THREAD

**Issue by cmxu2012** [Makeblock-official/Makeblock-Libraries#7]
https://github.com/Makeblock-official/Makeblock-Libraries/blob/master/makeblock/example/Firmware_for_Starter/IR_Ultrasonic/IR_Ultrasonic.ino

line 203 to 206,
  pinMode(13,OUTPUT);
  digitalWrite(13,HIGH);
  delay(300);
  digitalWrite(13,LOW);

what's the purpose of these code?
It makes PORT3 doens't work well when conneting some electronic module, such as IR Receiver.

**Comment by Makeblock-official** [comment]
The IR_Ultrasonic mode, only for Starter kit. and PORT_3 is map for Ultrasonic in its instructions. here these code just  used for power on indication(on setup), You are free to modify it.

**Comment by cmxu2012** [comment]
got it!  Thanks for the clarification.
